services:
  - type: web
    name: chat-app-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: your_backend_url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 