import "./globals.css";
import { Provider } from "@/components/ui/provider";
import ChatProvider from "../context/ChatProvider";
import { ChakraProvider } from "@chakra-ui/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <ChakraProvider>
            <ChatProvider>
              {children}
            </ChatProvider>
          </ChakraProvider>
        </Provider>
      </body>
    </html>
  );
}
